### ISSUE TITLE
use electron

### ISSUE THREAD

**Issue by webdev03** [meower-media-co/Meower-Desktop#9]
i dont know if u thought of it but electron would make cross platform ez (reason why is because idk what Meower-Linux is doing)

**Comment by Melt2002** [comment]
Meower Desktop will use nw.js for the time being, and will be released on Linux and Windows.

**Comment by webdev03** [comment]
OK
What about macOS devices like the one I am typing this on?

**Comment by Melt2002** [comment]
We don't plan on adding official macOS support, but if anyone in the future would like to make an unofficial version, that'd be okay.

**Comment by Melt2002** [comment]
Meower Desktop is becoming Meower Plus, so this will be closed.
